### ISSUE TITLE
import_psp crash: KeyError: 'href'

### ISSUE THREAD

**Issue by geckon** [geckon/zvanirna#3]
```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geckon/ws/zvanirna/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/geckon/ws/zvanirna/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geckon/ws/zvanirna/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geckon/ws/zvanirna/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/geckon/ws/zvanirna/spearch/management/commands/import_psp.py", line 193, in handle
    import_term('https://www.psp.cz/eknih/2017ps/stenprot/index.htm')
  File "/home/geckon/ws/zvanirna/spearch/management/commands/import_psp.py", line 51, in import_term
    import_day(urllib.parse.urljoin(url, dl['href']))
  File "/home/geckon/ws/zvanirna/spearch/management/commands/import_psp.py", line 109, in import_day
    urllib.parse.urljoin('https://www.psp.cz', a['href']))
  File "/home/geckon/ws/zvanirna/venv/lib64/python3.6/site-packages/bs4/element.py", line 1071, in __getitem__
    return self.attrs[key]
KeyError: 'href'
```

**Comment by geckon** [comment]
Apparently there can be links without `href` attribute in PSP session records to mark speech authors who aren't members of PSP and therefore don't have a "profile" page on PSP's web - e.g. Guvernér ČNB Jiří Rusnok or Předseda Sněmovny reprezentantů USA Paul Ryan.
